# Generated by Django 3.0 on 2020-03-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブフラグ')),
                ('is_staff', models.BooleanField(default=True, verbose_name='システム管理者フラグ')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='名前')),
                ('name_kana', models.CharField(max_length=200, null=True, verbose_name='ナマエ')),
                ('is_delete', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='削除日時')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'user',
            },
        ),
    ]
